start transaction;

-- Enable pgcrypto for the users table
CREATE EXTENSION pgcrypto;

-- Noodle makers
create table noodle_maker
(
	id integer primary key generated by default as identity,
	name text unique
);

-- Noodle listings
create table noodles
(
	id integer primary key generated by default as identity,
	name text, 
	maker_id integer references noodle_maker(id),
	barcode text,
	container_type text,		-- maybe this should be a reference but that seems excessive
	image_uri text
);

-- Individual reviews
create table noodle_review
(
	id integer primary key generated by default as identity,
	noodle_id integer references noodles(id),
	review_date date not null default current_date,
	score smallint not null,
	price money not null,
	review text
);

create table nms_user 
(
	id integer primary key generated by default as identity,
	username text not null unique,
	hashed_password text not null
);
--insert into nms_user (username, hashed_password) values ('test', crypt('%PLAINTEXT_PASS%', gen_salt('bf', 10)));
--SELECT (hashed_password = crypt('%PLAINTEXT_PASS%', hashed_password)) from nms_user where id = 1;

insert into noodle_maker (name) values ('Maruchan');
insert into noodle_maker (name) values ('Nissin - Cup Noodles');
insert into noodle_maker (name) values ('MAMA');
insert into noodle_maker (name) values ('Wang');
insert into noodle_maker (name) values ('Kang Shi Fu');


insert into noodles (maker_id, name, barcode, container_type, image_uri) values 
(1, 'Lime Chili Flavor with Shrimp', '041789001154', 'Cup', 'https://images.barcodelookup.com/3148/31480755-1.jpg');
insert into noodle_review(noodle_id, review_date, score, price, review) values 
(1, '2026-03-03', 70, 0.51, E'Flavor: 37/60\nConvenience: 29/30\nNoodle Quality: 4/10');

insert into noodles (maker_id, name, barcode, container_type, image_uri) values 
(1, 'Hot & Spicy Beef', '041789001420', 'Cup', 'https://images.barcodelookup.com/3148/31480731-1.jpg');
insert into noodle_review(noodle_id, review_date, score, price, review) values 
(2, '2026-03-05', 69, 0.58, E'Flavor: 36/60\nConvenience: 29/30\nNoodle Quality: 4/10');

insert into noodles (maker_id, name, barcode, container_type, image_uri) values 
(2, 'Stir Fry - Korean BBQ', '070662404034', 'Cup', 'https://images.barcodelookup.com/17397/173979890-1.jpg');
insert into noodle_review(noodle_id, review_date, score, price, review) values 
(3, '2026-03-06', 70, 1.08, E'Flavor: 42/60\nConvenience: 22/30\nNoodle Quality: 6/10');

insert into noodles (maker_id, name, barcode, container_type, image_uri) values 
(3, 'Artificial Pork', '052066000418', 'Cup', 'https://images.barcodelookup.com/3146/31466916-1.jpg');
insert into noodle_review(noodle_id, review_date, score, price, review) values 
(4, '2026-03-09', 75, 2.00, E'Flavor: 45/60\nConvenience: 25/30\nNoodle Quality: 5/10');

insert into noodles (maker_id, name, barcode, container_type, image_uri) values 
(4, 'Katsuo Udon Noodle', '087703023727', 'Bowl', 'https://images.barcodelookup.com/5345/53458880-1.jpg');
insert into noodle_review(noodle_id, review_date, score, price, review) values 
(5, '2026-03-11', 61, 4.00, E'Flavor: 48/60\nConvenience: 6/30\nNoodle Quality: 7/10');

insert into noodles (maker_id, name, barcode, container_type, image_uri) values 
(3, 'Shrimp Tom Yum', '052066000432', 'Cup', 'https://images.barcodelookup.com/3147/31473945-1.jpg');
insert into noodle_review(noodle_id, review_date, score, price, review) values 
(6, '2026-03-12', 77, 2.00, E'Flavor: 47/60\nConvenience: 25/30\nNoodle Quality: 5/10');

insert into noodles (maker_id, name, barcode, container_type, image_uri) values 
(5, 'Braised Artificial Beef', '6937962107000', 'Bowl', 'https://images.barcodelookup.com/30714/307142344-1.jpg');
insert into noodle_review(noodle_id, review_date, score, price, review) values 
(7, '2026-03-13', 71, 2.00, E'Flavor: 45/60\nConvenience: 20/30\nNoodle Quality: 6/10');


commit;

select no.name, no.barcode, no.image_uri, 
nm.name as maker, nr.review_date, nr.score, nr.review 
from noodle_review nr
join noodles no on nr.noodle_id = no.id 
join noodle_maker nm on no.maker_id = nm.id 
order by score desc;
