start transaction;

-- Noodle makers
create table noodle_maker
(
	id integer primary key generated by default as identity,
	name text unique
);

-- Noodle listings
create table noodles
(
	id integer primary key generated by default as identity,
	name text, 
	maker_id integer references noodle_maker(id),
	barcode text
);

-- Individual reviews
create table noodle_review
(
	id integer primary key generated by default as identity,
	noodle_id integer references noodles(id),
	review_date date not null default current_date,
	score smallint not null,
	review text
);

insert into noodle_maker (name) values ('Maruchan');
insert into noodle_maker (name) values ('Nissin - Cup Noodles');
insert into noodle_maker (name) values ('MAMA');

insert into noodles (maker_id, name, barcode) values (1, 'Lime Chili Flavor with Shrimp', '041789001154');
insert into noodles (maker_id, name, barcode) values (1, 'Hot & Spicy Beef', '041789001420');
insert into noodles (maker_id, name, barcode) values (2, 'Stir Fry - Korean BBQ', '070662404034');
insert into noodles (maker_id, name, barcode) values (3, 'Artificial Pork', '052066000418');

insert into noodle_review(noodle_id, review_date, score, review) values (1, '2026-03-03', 76, E'Flavor: 25/40\nValue ($0.51): 28/30\nConvenience: 19/20\nNoodle Quality: 4/10');
insert into noodle_review(noodle_id, review_date, score, review) values (2, '2026-03-05', 76, E'Flavor: 27/40\nValue ($0.58): 26/30\nConvenience: 19/20\nNoodle Quality: 4/10');
insert into noodle_review(noodle_id, review_date, score, review) values (3, '2026-03-06', 74, E'Flavor: 29/40\nValue ($1.08): 24/30\nConvenience: 15/20\nNoodle Quality: 6/10');
insert into noodle_review(noodle_id, review_date, score, review) values (4, '2026-03-09', 73, E'Flavor: 30/40\nValue ($2.00): 21/30\nConvenience: 17/20\nNoodle Quality: 5/10');
insert into noodle_review(noodle_id, review_date, score, review) values (1, '2026-03-09', 76, E'Flavor: 25/40\nValue ($0.51): 28/30\nConvenience: 19/20\nNoodle Quality: 4/10');

commit;

select no.name, nm.name as maker, nr.review_date, nr.score, nr.review 
from noodle_review nr
join noodles no on nr.noodle_id = no.id 
join noodle_maker nm on no.maker_id = nm.id;